/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateDriver: typeof import('./src/components/driver/CreateDriver.vue')['default']
    CreateTour: typeof import('./src/components/tour/CreateTour.vue')['default']
    DriverForm: typeof import('./src/components/DriverForm.vue')['default']
    DriverFormModal: typeof import('./src/components/driver/DriverFormModal.vue')['default']
    DriverList: typeof import('./src/components/driver/DriverList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TourForm: typeof import('./src/components/tour/TourForm.vue')['default']
    TourFormModal: typeof import('./src/components/tour/TourFormModal.vue')['default']
    TourList: typeof import('./src/components/tour/TourList.vue')['default']
  }
}
